### PR TITLE
Fixed bug when adding persons on registration page

### LINKED ISSUE #47: Frontend - fix Add persons button in RegistrationForm
Works, but the page refreshes and override the state somehow

### PR DESCRIPTION
**Pull request by joffe97**
Fix #47

### CODE REVIEW

File: GiEnJul/ClientApp/src/App.tsx [hunk 1]
```diff
@@ -6,12 +6,14 @@ import FetchData from './components/FetchData';
...
 import './custom.css'
+import Registration from './components/Registration';
 
 
 export default () => (
     <Layout>
         <Route exact path='/' component={Home} />
         <Route path='/fetch-data/:startDateIndex?' component={FetchData} />
         <Route path='/bli-giver' component={ SignUp }></Route>
+        <Route path='/registration' component={Registration} />
```
Comment (TheseusDeus) [inline GiEnJul/ClientApp/src/App.tsx:17]: Nice, u fied the pathing issue as well

**Review by TheseusDeus — APPROVED** [review]
