### PR TITLE
Fixed bugs on institution registration page

### LINKED ISSUE #253: Frontend - Cannot sumbit institution registration form if "alderstilpasset gave" is not selected.

### PR DESCRIPTION
**Pull request by joffe97**
Fix #253 

Fixed multiple bugs:
- Errorfields didn't reset (in some cases) after submitting.
- Persons states got mixed up.
- Recursion error when updating users (sometimes).
- Wishinput field didn't update parent component.

### CODE REVIEW

File: GiEnJul/ClientApp/src/components/institution/FormFood.tsx [hunk 1]
```diff
@@ -49,7 +49,7 @@ const FormDinner: FC<IFormDinner> = ({
   };
 
   useEffect(() => {
-    if (viewErrorTrigger) setViewError(true);
+    setViewError(!!viewErrorTrigger);
```
Comment (TheseusDeus) [inline GiEnJul/ClientApp/src/components/institution/FormFood.tsx:52]: why are you using double "!" here?

Comment (joffe97) [reply GiEnJul/ClientApp/src/components/institution/FormFood.tsx:52]: This is to convert from int to boolean. E.g. converts first to false then true.

Comment (TheseusDeus) [reply GiEnJul/ClientApp/src/components/institution/FormFood.tsx:52]: aah thats JS for you

**Review by TheseusDeus — APPROVED** [review]
