### PR TITLE
Selectform bug

### LINKED ISSUE #287: Frontend - Bug on mobile in the locations select, when registering giver
There is a bug in the location select on the giver registration page. This problem probably is in the SelectForm component. When locations is loaded on mobile, the first location is automatically selected (usually Bodø). This doesn't update the state of the chosen location though. Image below shows what happens when pressing continue. 
image
I would suggest to add an empty option for the SelectForm on mobile that is used as default. This option should disappear when a location is selected.

### PR DESCRIPTION
**Pull request by joffe97**
Fix #287
Fixed bug in selectform component on mobile, where it used a default value that didn't update in state.

### CODE REVIEW

**Review by Sommerli — APPROVED** [review]

File: GiEnJul/ClientApp/src/components/InputFields/SelectForm.tsx [hunk 1]
```diff
@@ -45,37 +77,22 @@ const SelectForm: FC<ISelect> = ({
...
-                value={o.value}
-                className="text-capitalize"
-              >
-                {o.text}
-              </option>
-            ) : (
-              <MenuItem
-                key={`${name}_${o.text}`}
-                value={o.value}
-                className="text-capitalize"
```
Comment (elisabethnetland) [inline GiEnJul/ClientApp/src/components/InputFields/SelectForm.tsx:73]: Small thing but the "text-capitalize" makes the first letter in each word to upper case. Would suggest to remove line 65 and73.
image
