### PR TITLE
Fix connect button

### LINKED ISSUE #528: Make a "Are you sure you want to connect" modal
As admin, when you want to connect a family to a giver, there should be an extra step of confirmation before the connection happens. 

For example a modal displaying the giver and family info, after clicking this button:

image

### PR DESCRIPTION
**Pull request by TTorgersen**
Closes #528 , and somewhat improves #569 (as you need to click a giver OR a family before the button appears)

### CODE REVIEW

File: ClientApp/src/components/admin/overview/OverviewMacro.tsx [hunk 1]
```diff
@@ -17,12 +17,25 @@ import { Alert } from "@material-ui/lab";
...
   giver: undefined,
-  recipient: {} as RecipientType,
+  recipient: undefined,
 };
 interface IOverviewMacro {
   location: string;
   accessToken: string;
 }
+
+const style = {
```
Comment (Sommerli) [inline ClientApp/src/components/admin/overview/OverviewMacro.tsx:27]: Please move this into the useStyles file, imported at line 13.

Name the style to fit its usage, then change line 168 to `<Box sx={classes.myStyle}>`

**Review by Sommerli — CHANGES_REQUESTED** [review]

File: ClientApp/src/components/admin/overview/ConnectButton.tsx [hunk 2]
```diff
@@ -1,18 +1,35 @@
...
 import { SelectedConnectionType } from "../../../common/components/Types";
+import { Grid, Typography, Modal, Box, Button} from "@material-ui/core";
+
 
 type ConnectButtonProps = {
   selectedConnection: SelectedConnectionType;
   connectGiverRecipient: () => void;
 };
 
+const style = {
```
Comment (Sommerli) [inline ClientApp/src/components/admin/overview/ConnectButton.tsx:12]: See comment before last commit :)

Comment (TTorgersen) [reply ClientApp/src/components/admin/overview/ConnectButton.tsx:12]: Yes, that previous commit was not supposed to be pushed to this merge :)

**Review by Sommerli — DISMISSED** [review]

**Review by HGodal — APPROVED** [review]
